### ISSUE TITLE
Alternate Use: as Project Dependency, as Filter, with Pre-minified JS & CSS, alternate Shortcode

### ISSUE THREAD

**Issue by ansonphong** [nextgenthemes/prism#1]
Hi There,
First off I really like the work you've done on this plugin, glad somebody took the time to implement this nicely for WordPress.

There are several features I'd like to add for alternate use case, to integrate into a pre-existing WordPress theme framework and including it as a dependency, rather than a plugin. Nothing needs to be modified in the structure, although in this context, there would be two alternate implementations. I'm happy to implement the changes myself and send a pull request, though I wanted to ask you first if you're open to other collaborators, or if I should fork the project.

---
### With Pre-minified JS & CSS

With the project I'm developing, the JS will be pre-minified into the source and pre-loaded already, and the CSS will be customized as part of the theme, so loading the JS and CSS files separately is not required. Also, I like to choose different settings for the minified `Prism.js` to support Ruby, Coffeescript, sass, etc. This also requires loading Prism separately.

I'll be adding a switch via a PHP definition something like:

``` php
public function is_preloaded(){
    return defined('PRISM_PRELOADED');
}
```

Then to cancel the `wp_enqueue_scripts` in the Class `__construct`, and in various locations where the scripts are enqueued, it's quite easy:

``` php
if(  $this->is_preloaded() ){
    add_action( 'wp_enqueue_scripts', array( $this, 'register_styles' ), 0 );
    add_action( 'wp_enqueue_scripts', array( $this, 'register_scripts' ), 0 );
    add_action( 'wp_enqueue_scripts', array( $this, 'maybe_load_prism' ) );
}
```

This way, I can just add this to the theme, and it won't have to load the scripts (again).

``` php
define('PRISM_PRELOADED', true);
```

---
### Allow for Alternate Shortcode Names

The shortcode is locked on with a name `prism` which is not intuitive for most users. I'd like to change the shortcode to `code`, without having to re-call `add_shortcode` on the class function with second shortcode called `code`.

In this way, the shortcode name can easily be filtered / changed from outside the class with a filter. Then in the several locations where the shortcode name is required, it's populated with a function like this:

``` php
public function shortcode_name(){
  return apply_filters('prism_shortcode_name','prism');
} 
```

Also some adjustments would have to be made to the `print_admin_javascript` function as well to reflect this.

---

Those are the two primary changes I'll be making to the source.

Let me know if you're open to a Pull Request or if I should just Fork it.

Thanks,
Phong

PS - I just noticed that the version number was : 20140418, which is exactly 1 year ago today, to the day. Wow, anyways glad I found the plugin. Heh.

**Comment by phongmedia** [comment]
Additionally, in the alternate implementation I'll be adding an option for the language names to be directly used as the shortcode.

For instance, instead of
```
[prism language=php]
...
[/prism]
```

You could use:
```
[php]
...
[/php]
```

**Comment by nextgenthemes** [comment]
I am glad of someone wants to enhance/improve my Code. I do not like the preloaded idea though, this should be done with native WP deregister_script, no need for a extra constant, but yes please do a PR.

Funny exactly one year, i thought of updating the bundled prism lately, but I currently just don't use it but will do later.

**Comment by phongmedia** [comment]
OK, understandable, its not ideal to use a PHP definition to customize it, for sure. Now that I think about it, it's not very proper at all. Using `deregister_script` seems also not ideal though.

What do you think about having the class constructor take an array of variables as key value pairs, with a set of defaults? This would leave it room to add-in other options in the future for the class to be invoked, as well as prepare for creating a WordPress Admin panel in which those variables could be customized.

This seems like the next logical step in the plugin's development. Let me know what you think.

**Comment by nextgenthemes** [comment]
Not sure I understand you, I like the idea of having shortcodes for every language. But do you want the plugin to have multiple versions of prism bundled?

**Comment by phongmedia** [comment]
Yea integrating Markdown plugin is ideal alternative option, so people don't need to use Jetpack. I also like the shortcodes, although having an option for either one I think would be the way to go, with a switch on which way the code is handled. Then this could be customized in the Admin panel.

The biggest limitation the plugin currently has, in my opinion, is that you can't customize your own build of Prism. The user is forced to use the language and theme choices that have been pre-selected. Also you don't want to force the user to load every language option, because most people won't need them all. 

Ideally the plugin would serve two purposes at the same time:

1. Serve as a simple one-click installation for most users to add Prism to their blog, with an admin panel for basic choices for the theme.

2. Serve as a submodule for other WordPress developers to integrate Prism into their themes. 

In the first instance, you could safely select a few of the most common languages and pre-bundle them.

In the second instance, developers will want to select their own custom Prism builds, and even customize the themes. In this case, the developer would add to that array which languages they selected 

If Prism has a RESTful API for retrieving the minified source, we could let users choose which languages they want to support in the options cache that locally. Unfortunately that's not the case, and so we can't really offer the option to customize exactly which languages are loaded.

![image](https://cloud.githubusercontent.com/assets/4825055/7219940/710a9ed0-e684-11e4-8d32-8b895a688e5e.png)

The developer would preselect these options they want in their theme, and then the languages array would reflect that.

```php
$vars['languages'] = array(
  'markup',
  'css',
  'c-like',
  'javascript',
  'less',
  'php',
  'ruby',
  'sass',
  'stylus'
);
```

**Comment by nextgenthemes** [comment]
There is not need for "Integrating" markdown in any way, the example above just works (with JP Markdown).

> The biggest limitation the plugin currently has, in my opinion, is that you can't customize your own build of Prism. The user is forced to use the language and theme choices that have been pre-selected.

Did you actually read [my plugin description](https://nextgenthemes.com/plugins/prism-syntax-highlighter-for-wordpress/)? Because you actually can use your very own prism version the exact way you want, just by uploading it to your uploads directory.

Honestly there are other plugins with all kinds of complicated IMO not needed options pages with all kinds of options. I coded this plugin as a very minimalistic plugin do actually avoid doing what you suggest because Prism has a ton of options that I not want to maintain and not feel its worth it. I do not see it as usefull for theme devs to include custom prism builds since they cant know what languages the users maybe want to use, have to update it ... but they actually can use their own custom prism builds, yet again with simple wordpress script and style registering without any need of a change to the plugin.

```php
add_action( 'wp_register_scripts', 'my_custom_prism', 1 );

function my_custom_prism() {
deregister_script( 'prism' ):
register_script( 'prism', .... ):

deregister_style( 'prism' ):
register_style( 'prism', .... ):
}
```
You seem to not payed attention, have no that much WordPress experience (in this area) and I would say you are over-thinking it. If you want to have some fancy options page then fork it but you may save yourself the trouble and just click yourself a prism version together on the official page and upload it. If you make a PR for individual shortcodes for the languages I will thankfully merge it, but even for that I personally not care that much because of my intended use of Markdown instead. Note the plugin has currently only 100+ users according to WordPress.org and you are the first person ever contact me about it.

Also how you want to do it? You want to generate a new .js file on the options page or load up a bunch of tiny individual files for each language and options? Means work and lots of extra HTTP requests ...

> If Prism had a RESTful API for retrieving the minified source
Yeah, there is probably a way to automate the process of getting the prism version customized from the official site (cURL?). If you would code something like this up I would be very interested - but again I would suggest save yourself the trouble ;)

**Comment by phongmedia** [comment]
Sure I understand deregister script, that's very basic WordPress functionality. For me the issue is more a matter of principle - that registering something and then deregistering it right after is making extra steps for PHP that's not necessary. From a app development standpoint it's not very graceful.

It seems like we have (slightly) different applications for this, as well as (slightly) different coding principles, and I've been trying to accommodate both types of applications. I honor the work you've already put into this.

So I'll go ahead and fork the project and then I'll send a link after that's finished and see what you think, and we could go from there.

**Comment by nextgenthemes** [comment]
Just so you know, I just noticed the prism site actually supports custom versions via get variables. So it should relatively easy to get custom versions from the site even without a real API.

http://prismjs.com/download.html?themes=prism-okaidia&languages=markup+css+clike+javascript+bash+less+php&plugins=line-highlight+line-numbers+wpd+show-language

**Comment by phongmedia** [comment]
How could that be done without scraping the data off the page?

**Comment by nextgenthemes** [comment]
I don't know. Maybe it can not but should not to big of a problem to scrape the page as it would only need to be done when someone changes "options".

Did you ever created something out of this?
