### ISSUE TITLE
Enable prism on the list of posts page?

### ISSUE THREAD

**Issue by xuhdev** [nextgenthemes/prism#2]
It looks like prism is only enabled in each post page. Is it possible to enable it on the page that previews multiple posts?

**Comment by nextgenthemes** [comment]
You can with `define( 'PRISM_ARCHIVE_SCAN', true)` in wp_config.php. I implemented this because I tought its good for performance reasons but now I think usinging `strpos` on all contents of prism html is uses should not really slow down a site noticeable.

I also use a updated unreleased version of this plugin in my site that removes this and always enables it. Also adding custom html classes to the wp-editor because I now use it many directly from the editor rather then with custom fields.

I released it, so you just need to update.

**Comment by xuhdev** [comment]
Thanks, upgrading works!
